apiVersion: v1
kind: Namespace
metadata:
  name: sd-fl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-1
  namespace: sd-fl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-1
  template:
    metadata:
      labels:
        app: client-1
    spec:
      containers:
        - name: client
          image: raiaraujo/sd-fl:fl-client-v2
          imagePullPolicy: IfNotPresent
          env:
            - name: CLIENT_ID
              value: "0"
          ports:
            - containerPort: 5000
          resources: 
            requests:
              cpu: "500m" 
              memory: "1Gi"
            limits:
              cpu: "1"    
              memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: client-1
  namespace: sd-fl
spec:
  selector:
    app: client-1
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-2
  namespace: sd-fl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-2
  template:
    metadata:
      labels:
        app: client-2
    spec:
      containers:
        - name: client
          image: raiaraujo/sd-fl:fl-client-v2
          imagePullPolicy: IfNotPresent
          env:
            - name: CLIENT_ID
              value: "1"
          ports:
            - containerPort: 5000
          resources: 
            requests:
              cpu: "250m" 
              memory: "512Mi"
            limits:
              cpu: "500m" 
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: client-2
  namespace: sd-fl
spec:
  selector:
    app: client-2
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-3
  namespace: sd-fl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-3
  template:
    metadata:
      labels:
        app: client-3
    spec:
      containers:
        - name: client
          image: raiaraujo/sd-fl:fl-client-v2
          imagePullPolicy: IfNotPresent
          env:
            - name: CLIENT_ID
              value: "2"
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m" 
              memory: "256Mi"
            limits:
              cpu: "250m" 
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: client-3
  namespace: sd-fl
spec:
  selector:
    app: client-3
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
---

# storage.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metrics-pvc
  namespace: sd-fl
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-access
  namespace: sd-fl
spec:
  replicas: 1
  selector:
    matchLabels: { app: metrics-access }
  template:
    metadata: { labels: { app: metrics-access } }
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["sleep", "infinity"]
          volumeMounts:
            - name: metrics
              mountPath: /data
      volumes:
        - name: metrics
          persistentVolumeClaim:
            claimName: metrics-pvc
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: sd-fl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: orchestrator
          image: raiaraujo/sd-fl:orchestrator-v2
          imagePullPolicy: IfNotPresent
          command: ["python", "-u", "-m", "orchestrator.orchestrator"]
          env:
            - name: PYTHONPATH
              value: "/app"
          resources:
            requests: { cpu: "250m", memory: "512Mi" }
            limits:   { cpu: "1",    memory: "1Gi" }
          volumeMounts:
            - name: metrics
              mountPath: /app/metrics
      volumes:
        - name: metrics
          persistentVolumeClaim:
            claimName: metrics-pvc